---

- fail:
    msg: "bind_key is not set !"
  when: bind_key is not defined or not bind_key

- fail:
    msg: "bind_key_dir is not set !"
  when: bind_key_dir is not defined or not bind_key_dir


- block:

    - name: deploy key
      template:
        src: "bind/key.template"
        dest: "{{ bind_key_dir }}/{{ bind_key.name }}"
        owner: "{{ bind_key_owner | d('root') }}"
        group: "{{ bind_key_group | d(root_group) }}"
        mode: "{{ bind_key_mode | d('0640') }}"
      register: t_dns_bind_key_deploy
      notify: "{{ dns_bind_service_type }} restart bind"

  when: bind_key.secret is defined and bind_key.secret


- block:

    - name: stat keys
      stat:
        path: "{{ bind_key_dir }}/{{ bind_key.name }}"
      register: t_dns_bind_key_stat

    - name: create key
      shell:
        cmd: "tsig-keygen -a {{ bind_key.algorithm | default(dns_bind_key_algorithm) }} \"{{ bind_key.name }}\" > \"{{ bind_key_dir }}/{{ bind_key.name }}\""
      when: not t_dns_bind_key_stat.stat.exists
      register: t_dns_bind_key_create
      notify: "{{ dns_bind_service_type }} restart bind"

    - name: key permission
      file:
        path: "{{ bind_key_dir }}/{{ bind_key.name }}"
        owner: "{{ bind_key_owner | d('root') }}"
        group: "{{ bind_key_group | d(root_group) }}"
        mode: "{{ bind_key_mode | d('0640') }}"

  when: bind_key.secret is not defined or not bind_key.secret


- name: bind_key update
  set_fact:
    t_bind_key_update: "{{ t_dns_bind_key_deploy.changed or t_dns_bind_key_create.changed }}"
