---

- name: create named db dirs
  file:
    path: "{{ dns_bind_conf_dir }}/{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: master, owner: root, group: "{{ root_group }}", mode:
  "0755" }
    - { path: slave, owner: "{{ dns_bind_user }}", group: "{{
  dns_bind_group }}", mode: "0755" }
    - { path: working, owner: "{{ dns_bind_user }}", group: "{{
  dns_bind_group }}", mode: "0755" }
    - { path: dynamic, owner: "{{ dns_bind_user }}", group: "{{
  dns_bind_group }}", mode: "0755" }

- name: deploy standard master db
  copy:
    src: "named/master/{{ item.name }}"
    dest: "{{ dns_bind_conf_dir }}/master/{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { name: empty.db, owner: root, group: "{{ root_group }}", mode:
  "0644" }
    - { name: localhost-forward.db, owner: root, group: "{{ root_group }}", mode:
  "0644" }
    - { name: localhost-reverse.db, owner: root, group: "{{ root_group }}", mode:
  "0644" }

- name: deploy bind.keys from internet
  get_url:
    url: "{{ dns_bind_keys_url }}"
    dest: "{{ dns_bind_conf_dir }}/bind.keys"
    mode: '0644'
    owner: root
    group: "{{ root_group }}"
  failed_when: false
  register: t_bind_keys_internet

- debug:
    msg: "{{ t_bind_keys_internet }}"

- name: deploy bind.keys from local copy
  copy:
    src: "named/{{ dns_bind_keys_name }}"
    dest: "{{ dns_bind_conf_dir }}/bind.keys"
    owner: root
    group: "{{ root_group }}"
    mode: "0644"
  when: t_bind_keys_internet.status_code != 200

- name: deploy named.root from internet
  get_url:
    url: "{{ dns_bind_named_root_url }}"
    dest: "{{ dns_bind_conf_dir }}/named.root"
    mode: '0644'
    owner: root
    group: "{{ root_group }}"
  failed_when: false
  register: t_named_root_internet

- name: deploy named.root from local copy
  copy:
    src: "named/{{ dns_bind_named_root_name }}"
    dest: "{{ dns_bind_conf_dir }}/named.root"
    owner: root
    group: "{{ root_group }}"
    mode: "0644"
  when: t_named_root_internet.status_code != 200

  
# named.conf

# rndc.conf
