---

- name: zone filepath
  set_fact:
    t_dns_bind_view_zone_filepath: "{{ zone['file'] | d( dns_bind_conf_dir + '/' + zone['type'] + '/' + 'db.' + view_label + '.' + zone['name'] ) }}"

- name: stat zone
  stat:
    path: "{{ t_dns_bind_view_zone_filepath }}"
  register: t_dns_bind_view_zone_stat

- name: deploy custom zone
  template:
    src: "bind/db/db.template"
    dest: "{{ t_dns_bind_view_zone_filepath }}"
    owner: "{{ item.owner | d(dns_bind_user) }}"
    group: "{{ item.group | d(dns_bind_group) }}"
    mode: "{{ item.mode | d('0644') }}"
  when: not t_dns_bind_view_zone_stat.stat.exists


- name: check zone
  command: "named-checkzone {{ zone['name'] }} {{ t_dns_bind_view_zone_filepath }}"
  changed_when: false
  failed_when: false
  register: t_dns_bind_checkzone

- fail:
    msg: "{{ t_dns_bind_checkzone }}"
  when: t_dns_bind_checkzone.failed
